# theme.py
#
# Hand-written, unlike the other modules in this package (those starting with
# `gui_` are generated by generate_gui.sh from resources/ui/*.ui and must not
# be edited directly). This file is plain Python and safe to edit.

from PySide6 import QtWidgets

DARK_STYLESHEET = """
QWidget {
  background-color: #2b2b2b;
  color: #dcdcdc;
  selection-background-color: #3a6ea5;
  selection-color: #ffffff;
}

QMainWindow, QDialog {
  background-color: #2b2b2b;
}

QGroupBox {
  border: 1px solid #555555;
  border-radius: 3px;
  margin-top: 8px;
  padding-top: 6px;
}

QGroupBox::title {
  subcontrol-origin: margin;
  left: 8px;
  padding: 0 4px;
  color: #dcdcdc;
}

QLabel {
  background-color: transparent;
}

QLineEdit, QListWidget, QTableWidget, QComboBox,
QSpinBox, QDoubleSpinBox, QAbstractSpinBox {
  background-color: #3c3f41;
  color: #dcdcdc;
  border: 1px solid #555555;
  border-radius: 2px;
}

QTableWidget {
  gridline-color: #555555;
}

QHeaderView::section {
  background-color: #454545;
  color: #dcdcdc;
  padding: 4px;
  border: 1px solid #555555;
}

QComboBox QAbstractItemView {
  background-color: #3c3f41;
  color: #dcdcdc;
  selection-background-color: #3a6ea5;
}

QPushButton {
  background-color: #454545;
  color: #dcdcdc;
  border: 1px solid #5a5a5a;
  border-radius: 3px;
  padding: 4px 10px;
}

QPushButton:hover {
  background-color: #525252;
}

QPushButton:pressed {
  background-color: #3a3a3a;
}

QPushButton:disabled {
  color: #777777;
  background-color: #3a3a3a;
}

QCheckBox, QRadioButton {
  background-color: transparent;
  spacing: 6px;
}

QMenuBar {
  background-color: #2b2b2b;
  color: #dcdcdc;
}

QMenuBar::item:selected {
  background-color: #3a6ea5;
}

QMenu {
  background-color: #3c3f41;
  color: #dcdcdc;
  border: 1px solid #555555;
}

QMenu::item:selected {
  background-color: #3a6ea5;
}

QStatusBar {
  background-color: #2b2b2b;
  color: #dcdcdc;
}

QToolTip {
  background-color: #454545;
  color: #dcdcdc;
  border: 1px solid #5a5a5a;
}

QScrollBar:vertical, QScrollBar:horizontal {
  background-color: #2b2b2b;
  border: none;
}

QScrollBar::handle:vertical, QScrollBar::handle:horizontal {
  background-color: #5a5a5a;
  border-radius: 3px;
}

QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {
  background-color: #6e6e6e;
}

QScrollBar::add-line, QScrollBar::sub-line {
  height: 0px;
  width: 0px;
}
"""

_ORIGINAL_STYLE_PROPERTY = "shortcircuit_original_style"


def apply_theme(app: QtWidgets.QApplication, dark: bool) -> None:
  """
  Apply or clear the dark theme on the whole application.

  Qt style sheets interact poorly with Windows' native widget style (combo
  box/spin box arrows, checkboxes, etc. don't fully respect QSS colors under
  it), so dark mode also switches the base QStyle to Fusion, which is fully
  stylesheet-driven. The original style is restored when dark mode is
  turned back off. The original style name is stashed as a dynamic Qt
  property on the application object rather than module state, since it
  needs to survive across calls without relying on a Python global.
  """
  if app.property(_ORIGINAL_STYLE_PROPERTY) is None:
    app.setProperty(_ORIGINAL_STYLE_PROPERTY, app.style().objectName())

  if dark:
    fusion_style = QtWidgets.QStyleFactory.create("Fusion")
    if fusion_style is not None:
      app.setStyle(fusion_style)
    app.setStyleSheet(DARK_STYLESHEET)
  else:
    original_style = QtWidgets.QStyleFactory.create(
      app.property(_ORIGINAL_STYLE_PROPERTY)
    )
    if original_style is not None:
      app.setStyle(original_style)
    app.setStyleSheet("")
